name: Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  APP_URL: http://127.0.0.1
  APP_PORT: 8000
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set Laravel environment variables
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Create testing database
        run: |
          mysql --host=127.0.0.1 --port=3306 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS testing;"
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: password

      - name: Run database migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password

      - name: Seed the database with test data for e2e
        run: php artisan db:seed --force

      - name: Build assets
        run: npm run build

      - name: Run Laravel server
        run: php artisan serve --host=0.0.0.0 --port=8000 &
        env:
          APP_ENV: testing

      - name: Run PHP tests
        run: php artisan test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
